#### Conv-TasNet Setting
name: Conv_Tasnet
gpu_ids: [0]
# epochs: 10

#### training settings: learning rate scheme, loss
train:
  optimizer: adam
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5
  logging_period: 200
  clip_norm: 200
  num_epochs: 50
  checkpoint: Conv-TasNet-checkpoints

optimizer_kwargs:
  lr: !!float 1e-3
  weight_decay: !!float 1e-5

#### network configure
net_conf:
  N: 512
  L: 16
  B: 128
  H: 512
  P: 3
  X: 8
  R: 3
  norm: gln
  num_spks: 2
  activate: relu
  causal: false

#### resume model
resume:
  path: ./Conv-TasNet
  resume_state: false